### ISSUE TITLE
Quicksearch is broken

### ISSUE THREAD

**Issue by Praesidiarius** [OnePlc/PLC_X_Core#14]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.17

#### Summary

as soon as you start entering a query, the search is broken
response is 
```php
Message:

    Statement could not be executed (42S22 - 1054 - Unknown column 'username' in 'where clause')

Stack trace:

    #0 /var/www/plc/vendor/laminas/laminas-db/src/TableGateway/AbstractTableGateway.php(239): Laminas\Db\Adapter\Driver\Pdo\Statement->execute()
    #1 /var/www/plc/vendor/laminas/laminas-db/src/TableGateway/AbstractTableGateway.php(207): Laminas\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Laminas\Db\Sql\Select))
    #2 /var/www/plc/vendor/oneplace/oneplace-user/src/Model/ApikeyTable.php(92): Laminas\Db\TableGateway\AbstractTableGateway->selectWith(Object(Laminas\Db\Sql\Select))
    #3 /var/www/plc/module/Application/src/Controller/IndexController.php(478): OnePlace\User\Model\ApikeyTable->fetchAll(false, Array)
    #4 /var/www/plc/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Application\Controller\IndexController->quicksearchAction()
    #5 /var/www/plc/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
```

#### Current behavior

its broken, you can't find anything

#### How to reproduce

just start searching in quicksearch

#### Expected behavior

it should show relevant results

**Comment by Praesidiarius** [comment]
seems to be caused by the new apikey form - skip it from quicksearch
